# Generated by Django 2.1.1 on 2019-01-12 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_doctor', models.BooleanField(default=False, verbose_name='Doctor')),
                ('is_patient', models.BooleanField(default=True, verbose_name='Patient')),
            ],
        ),
    ]
