# Generated by Django 2.1.1 on 2019-02-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='NMC_Number',
            field=models.IntegerField(default=12345),
        ),
    ]
